# Generated by Django 6.0.2 on 2026-02-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
