# Generated by Django 6.0.2 on 2026-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_resume_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_viewed',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
