# Generated by Django 6.0.2 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
